baseURL = 'https://example.org/'
languageCode = 'en'
title = 'Miguel Angel Berbel'
disableKinds = ['taxonomy', 'term', 'RSS']
enableRobotsTXT = true
[outputs]
  home = ['HTML']
  page = ['HTML']
[markup.goldmark.renderer]
  unsafe = false
[caches.images]
  dir = ':cacheDir/images'
